server:
  port: 7001
spring:
  main:
    #允许bean定义重写
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html