server:
  port: 8001

spring:
  main:
    #允许bean定义重写
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300

#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"